// <auto-generated />
using System;
using LibraryProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260909192804_updateBookAndBorrow")]
    partial class updateBookAndBorrow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksBId")
                        .HasColumnType("int");

                    b.Property<int>("GenresGId")
                        .HasColumnType("int");

                    b.HasKey("BooksBId", "GenresGId");

                    b.HasIndex("GenresGId");

                    b.ToTable("BookGenre");
                });

            modelBuilder.Entity("LibraryProject.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LibraryProject.Data.Models.Author", b =>
                {
                    b.Property<int>("AId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AId"));

                    b.Property<int>("Birthyear")
                        .HasColumnType("int");

                    b.Property<int>("Deathyear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AId");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            AId = 1,
                            Birthyear = 1898,
                            Deathyear = 1963,
                            FirstName = "C.S.",
                            LastName = "Lewis"
                        },
                        new
                        {
                            AId = 2,
                            Birthyear = 1892,
                            Deathyear = 1973,
                            FirstName = "J.R.R.",
                            LastName = "Tolkien"
                        },
                        new
                        {
                            AId = 3,
                            Birthyear = 1973,
                            Deathyear = 0,
                            FirstName = "Guy",
                            LastName = "Haley"
                        },
                        new
                        {
                            AId = 4,
                            Birthyear = 1989,
                            Deathyear = 0,
                            FirstName = "John",
                            LastName = "French"
                        },
                        new
                        {
                            AId = 5,
                            Birthyear = 1990,
                            Deathyear = 0,
                            FirstName = "Robert",
                            LastName = "Rath"
                        },
                        new
                        {
                            AId = 6,
                            Birthyear = 1965,
                            Deathyear = 0,
                            FirstName = "Dan",
                            LastName = "Abnett"
                        },
                        new
                        {
                            AId = 7,
                            Birthyear = 1920,
                            Deathyear = 1986,
                            FirstName = "Frank",
                            LastName = "Herbert"
                        },
                        new
                        {
                            AId = 8,
                            Birthyear = 1971,
                            Deathyear = 0,
                            FirstName = "Justin D.",
                            LastName = "Hill"
                        });
                });

            modelBuilder.Entity("LibraryProject.Data.Models.Book", b =>
                {
                    b.Property<int>("BId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BId"));

                    b.Property<int>("AId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<int>("PId")
                        .HasColumnType("int");

                    b.Property<int>("Pagecount")
                        .HasColumnType("int");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BId");

                    b.HasIndex("AId");

                    b.HasIndex("PId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BId = 1,
                            AId = 1,
                            Description = "",
                            Edition = 1,
                            PId = 2,
                            Pagecount = 208,
                            PublishYear = 1950,
                            Stock = 2,
                            Title = "The Lion, the Witch and the Wardrobe"
                        },
                        new
                        {
                            BId = 2,
                            AId = 2,
                            Description = "",
                            Edition = 1,
                            PId = 3,
                            Pagecount = 300,
                            PublishYear = 1937,
                            Stock = 2,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            BId = 3,
                            AId = 3,
                            Description = "",
                            Edition = 2,
                            PId = 1,
                            Pagecount = 432,
                            PublishYear = 2021,
                            Stock = 1,
                            Title = "Dark Imperium"
                        },
                        new
                        {
                            BId = 4,
                            AId = 3,
                            Description = "",
                            Edition = 2,
                            PId = 1,
                            Pagecount = 401,
                            PublishYear = 2022,
                            Stock = 1,
                            Title = "Dark Imperium: Plague War"
                        },
                        new
                        {
                            BId = 5,
                            AId = 3,
                            Description = "",
                            Edition = 2,
                            PId = 1,
                            Pagecount = 431,
                            PublishYear = 2022,
                            Stock = 1,
                            Title = "Dark Imperium: Godblight"
                        },
                        new
                        {
                            BId = 6,
                            AId = 7,
                            Description = "",
                            Edition = 4,
                            PId = 4,
                            Pagecount = 577,
                            PublishYear = 2015,
                            Stock = 1,
                            Title = "Dune"
                        },
                        new
                        {
                            BId = 7,
                            AId = 7,
                            Description = "",
                            Edition = 4,
                            PId = 4,
                            Pagecount = 293,
                            PublishYear = 2017,
                            Stock = 2,
                            Title = "Dune Messiah"
                        },
                        new
                        {
                            BId = 8,
                            AId = 7,
                            Description = "",
                            Edition = 4,
                            PId = 4,
                            Pagecount = 423,
                            PublishYear = 2021,
                            Stock = 2,
                            Title = "Children of Dune"
                        },
                        new
                        {
                            BId = 9,
                            AId = 7,
                            Description = "",
                            Edition = 3,
                            PId = 4,
                            Pagecount = 420,
                            PublishYear = 2020,
                            Stock = 2,
                            Title = "God Emperor of Dune"
                        },
                        new
                        {
                            BId = 10,
                            AId = 5,
                            Description = "",
                            Edition = 1,
                            PId = 1,
                            Pagecount = 656,
                            PublishYear = 2023,
                            Stock = 1,
                            Title = "The Fall of Cadia"
                        },
                        new
                        {
                            BId = 11,
                            AId = 5,
                            Description = "",
                            Edition = 1,
                            PId = 1,
                            Pagecount = 464,
                            PublishYear = 2022,
                            Stock = 1,
                            Title = "Assassinorum: Kingmaker"
                        },
                        new
                        {
                            BId = 12,
                            AId = 4,
                            Description = "",
                            Edition = 1,
                            PId = 1,
                            Pagecount = 192,
                            PublishYear = 2024,
                            Stock = 1,
                            Title = "Cypher: Lord of the Fallen"
                        },
                        new
                        {
                            BId = 13,
                            AId = 4,
                            Description = "",
                            Edition = 2,
                            PId = 1,
                            Pagecount = 880,
                            PublishYear = 2024,
                            Stock = 1,
                            Title = "Ahriman: The Omnibus"
                        },
                        new
                        {
                            BId = 14,
                            AId = 6,
                            Description = "",
                            Edition = 2,
                            PId = 1,
                            Pagecount = 880,
                            PublishYear = 2022,
                            Stock = 2,
                            Title = "The Founding"
                        },
                        new
                        {
                            BId = 15,
                            AId = 8,
                            Description = "",
                            Edition = 1,
                            PId = 1,
                            Pagecount = 1079,
                            PublishYear = 2023,
                            Stock = 1,
                            Title = "Minka Lesk: The Last Whiteshield"
                        },
                        new
                        {
                            BId = 16,
                            AId = 2,
                            Description = "",
                            Edition = 1,
                            PId = 3,
                            Pagecount = 423,
                            PublishYear = 1937,
                            Stock = 3,
                            Title = "The Fellowship of the Ring"
                        },
                        new
                        {
                            BId = 17,
                            AId = 2,
                            Description = "",
                            Edition = 1,
                            PId = 3,
                            Pagecount = 352,
                            PublishYear = 1937,
                            Stock = 3,
                            Title = "The Two Towers"
                        },
                        new
                        {
                            BId = 18,
                            AId = 2,
                            Description = "",
                            Edition = 1,
                            PId = 3,
                            Pagecount = 416,
                            PublishYear = 1937,
                            Stock = 3,
                            Title = "The Return of the King"
                        });
                });

            modelBuilder.Entity("LibraryProject.Data.Models.BorrowedBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BId")
                        .HasColumnType("int");

                    b.Property<string>("UId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BorrowedBook");
                });

            modelBuilder.Entity("LibraryProject.Data.Models.Genre", b =>
                {
                    b.Property<int>("GId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GId");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            GId = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            GId = 2,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            GId = 3,
                            Name = "Horror"
                        },
                        new
                        {
                            GId = 4,
                            Name = "Romance"
                        },
                        new
                        {
                            GId = 5,
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("LibraryProject.Data.Models.Publisher", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PId");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            PId = 1,
                            Name = "Black Library"
                        },
                        new
                        {
                            PId = 2,
                            Name = "Geoffrey Bles"
                        },
                        new
                        {
                            PId = 3,
                            Name = "George Allen & Unwin"
                        },
                        new
                        {
                            PId = 4,
                            Name = "Hodder & Stoughton Ltd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("varbinary(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("LibraryProject.Data.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryProject.Data.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresGId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryProject.Data.Models.Book", b =>
                {
                    b.HasOne("LibraryProject.Data.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryProject.Data.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LibraryProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LibraryProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("LibraryProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<long>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LibraryProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryProject.Data.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
